const { test, expect } = require('@playwright/test');
test('I can set up one temporary patient and return to correct their details', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('link', { name: 'Get started' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByText('Enter their name.', { exact: true })).toBeVisible();
  await page.getByLabel('Their name').fill('   ');
  await page.getByLabel('Your relationship to them').fill('Daughter');
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByText('Enter their name.', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Your relationship to them')).toHaveValue('Daughter');
  await page.getByLabel('Their name').fill('  Mira Example  ');
  await page.screenshot({ path: '.impeccable/review/setup-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('heading', { name: 'What happened?' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Mira Example' })).toBeVisible();
  await page.screenshot({ path: '.impeccable/review/capture-entry-mobile.png', fullPage: true });
  await page.getByRole('link', { name: 'Back' }).click();
  await expect(page.getByLabel('Their name')).toHaveValue('Mira Example');
  await page.getByLabel('Their name').fill('<b>Fictional person</b>');
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('heading', { name: '<b>Fictional person</b>' })).toBeVisible();
  expect(await page.locator('h2 b').count()).toBe(0);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Who are you keeping track of?' })).toBeVisible();
  await expect(page.getByLabel('Their name')).toHaveValue('');
  await expect(page.getByLabel('Your relationship to them')).toHaveValue('');
  await page.setViewportSize({ width: 320, height: 568 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: '.impeccable/review/setup-desktop.png', fullPage: true });
});
