import { analyticsEnabled,analyticsReady,setAnalytics } from './analytics.js';
export function mountPrivacy(root,session,onBack,backLabel){
  let disposed=false,busy=false,enabled=analyticsEnabled(),error='',notice='';
  function draw(){if(disposed)return;
    root.innerHTML=`<section class="screen privacy-screen" aria-labelledby="title"><button class="text-action back" id="privacy-back" type="button">${backLabel || (session.isAuthenticated?'Back to timeline':'Back')}</button><h1 id="title" tabindex="-1">Your notes. Your choice.</h1><p>Here’s how CareNama looks after the information you share.</p>
      <section class="privacy-section"><h2>What we keep</h2><p>Convex stores your account email, the person’s name and relationship, and the updates you choose to save. Updates include your original words or voice transcript, recorded details, timing and corrections.</p><p>Before sign-in, your unsaved update stays only in this open page. Audio is sent for transcription and isn’t kept in your health record. Summary drafts and edits stay in this page.</p></section>
      <section class="privacy-section"><h2>Who helps process it</h2><ul><li><strong>Convex</strong> hosts CareNama, signs you in and stores your record.</li><li><strong>Sarvam</strong> transcribes voice updates and helps organise your words and prepare summaries.</li><li><strong>Resend</strong> sends sign-in and account-deletion codes to your email. These emails contain no health notes.</li><li><strong>Mixpanel, in the EU</strong> helps us understand which parts of CareNama are used. It receives actions such as saving an update or copying a summary, using a random ID. It receives no names, emails, health words, readings, medicine names or location.</li></ul><p>We don’t record your screen, replay sessions or track what you type. Sharing sends text only when you choose Share or Copy; the app you choose then handles it.</p></section>
      <section class="privacy-section"><h2>Help improve CareNama</h2><p>Optional usage tracking is on by default. Turning it off won’t change how your health record works.${session.isAuthenticated?' This choice applies to your signed-in account on all devices.':' This choice applies to this browser and carries into your account when you sign in.'}</p><button class="privacy-toggle" type="button" role="switch" aria-checked="${enabled}" aria-describedby="privacy-help" id="analytics-switch" ${busy?'disabled':''}><span>Usage tracking</span><span class="toggle-state">${busy?'Saving…':enabled?'On':'Off'}</span></button><p class="hint" id="privacy-help">${enabled?'Only the limited usage information described above is sent.':'New usage events won’t be sent. Previously sent events aren’t removed by this switch.'}</p><p class="error" role="alert" ${error?'':'hidden'}>${error}</p><p role="status" class="hint" ${notice?'':'hidden'}>${notice}</p></section>
      <section class="privacy-section"><h2>Keeping or deleting your record</h2><p>Your saved notes remain until you delete them. You can change or delete individual updates from your timeline. Account → Delete account and record removes your account, the person and every saved update permanently after a fresh email code.</p><p>We also request deletion of the Mixpanel profile linked to your random account ID. If Mixpanel is unavailable, we retry this separately; it doesn’t delay deletion of your health record. Profile deletion doesn’t erase previously recorded usage events. Copies you shared elsewhere remain in the apps or with the people you chose.</p></section><p class="hint privacy-storage">This browser keeps sign-in information, a returning-record hint, your tracking choice and a random usage ID. Health notes aren’t saved in browser storage.</p></section>`;
    root.querySelector('#privacy-back').onclick=onBack;
    root.querySelector('#analytics-switch').onclick=async()=>{if(busy)return;busy=true;error='';notice='';draw();try{await setAnalytics(!enabled,session);if(disposed)return;enabled=!enabled;notice=enabled?'Usage tracking is on.':'Usage tracking is off.';}catch{if(disposed)return;error='We couldn’t save your choice. Try again.';}busy=false;draw();root.querySelector('#analytics-switch').focus();};
  }
  draw();root.querySelector('h1').focus();
  if(session.isAuthenticated){busy=true;draw();analyticsReady().then(()=>session.getAnalyticsPreference()).then(value=>{if(disposed)return;enabled=value;busy=false;draw();}).catch(()=>{if(disposed)return;busy=false;error='We couldn’t load your account choice. Try again by reopening Privacy.';draw();});}
  return()=>{disposed=true;};
}
