import { escape, captureLabel } from './observation-display.js';
import { validDate } from '../convex/lib/observationTiming.ts';

export function mountPeriodSummary(root,session,patient,onBack) {
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(Date.now());
  let start=new Date(Date.parse(`${today}T12:00:00Z`)-13*86400000).toISOString().slice(0,10),end=today,busy=false,error='',result=null,disposed=false;
  function dateLabel(value){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));}
  function source(source){return `<li><div><p class="fact-text">${escape(source.event)}</p><p class="fact-time">${source.date?escape(dateLabel(source.date)):'Timing not known'}${source.when && !/^(today|yesterday|Not specified|Unknown)$/i.test(source.when)?` · ${escape(source.when)}`:''}</p><details class="summary-source"><summary>View source</summary><p>Evidence: ${escape(source.evidence)}</p>${source.edited?'<p>Corrected by you.</p>':''}<p>${escape({present:'Explicitly present',absent:'Explicitly absent',uncertain:'Uncertain'}[source.polarity] || 'Uncertain')}</p><p class="hint">Captured on ${escape(captureLabel(source))}</p><p class="original-update">${escape(source.supportingWords)}</p></details></div></li>`;}
  function draw(){if(disposed)return;
    root.innerHTML=`<section class="screen period-summary" aria-labelledby="title"><button class="text-action back" id="summary-back" type="button">Back to timeline</button><h1 id="title" tabindex="-1">${escape(patient.name)}’s notes for a period</h1><p>Bring the recorded details together when you need to remember.</p><form id="summary-period" novalidate><div class="period-dates"><div><label for="period-start">From</label><input id="period-start" type="date" value="${start}" ${busy?'disabled':''}></div><div><label for="period-end">To</label><input id="period-end" type="date" value="${end}" ${busy?'disabled':''}></div></div><p class="hint">Dates refer to when things happened. Undated details recorded in this period appear separately.</p><button class="primary account-start" type="submit" ${busy?'disabled':''}>${busy?'Preparing your summary…':'Prepare summary'}</button></form>${busy?'<p role="status">Reading the saved notes for this period.</p>':''}${error?`<p class="error" role="alert">${escape(error)}</p>`:''}
    ${result?`<div class="period-result" aria-live="polite"><h2>${escape(dateLabel(start))} to ${escape(dateLabel(end))}</h2>
      ${result.status==='empty'?'<p>There are no dated updates to summarise for this period.</p>':result.status==='too_many'?`<p>${escape(result.message)}</p>`:`<p class="hint">Based on ${result.recordCount} saved ${result.recordCount===1?'update':'updates'}. Prepared ${escape(captureLabel({capturedAt:result.generatedAt,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}))}.</p>${result.recordCount<=2?'<p class="summary-limited">This is based on only a few updates, so it gives a limited picture of this period.</p>':''}${result.groups.map(group=>`<section class="summary-section"><h3>${escape(group.title)}</h3><ul class="update-facts">${group.keys.map(key=>source(result.sources.find(item=>item.key===key))).join('')}</ul></section>`).join('')}`}
      ${result.undatedCount?`<details class="undated-summary"><summary>${result.undatedCount} ${result.undatedCount===1?'detail with uncertain timing':'details with uncertain timing'}</summary><p class="hint">These were recorded in this period, but we don’t know when they happened. They are separate from the dated summary.</p><ul class="update-facts">${result.undated.map(source).join('')}</ul>${result.undatedCount>result.undated.length?`<p class="hint">Showing the first ${result.undated.length} undated details.</p>`:''}</details>`:''}</div>`:''}</section>`;
    root.querySelector('#summary-back').onclick=()=>{disposed=true;onBack();};
    function change(){start=root.querySelector('#period-start').value;end=root.querySelector('#period-end').value;result=null;error='';root.querySelector('.period-result')?.remove();root.querySelector('[role="alert"]')?.remove();}
    root.querySelector('#period-start').oninput=change;root.querySelector('#period-end').oninput=change;
    root.querySelector('#summary-period').onsubmit=async event=>{event.preventDefault();if(busy)return;if(!validDate(start)||!validDate(end)||start>end){error='Choose valid dates, with the start before the end.';result=null;draw();return;}busy=true;error='';result=null;draw();try{const response=await session.generateSummary({patientId:patient.id,start,end});if(disposed)return;result=response;}catch{if(disposed)return;error='Busy right now. Try again in a few minutes. Your saved notes are still there.';}busy=false;draw();root.querySelector('.period-result h2')?.setAttribute('tabindex','-1');root.querySelector('.period-result h2')?.focus();};
  }
  draw();root.querySelector('h1').focus();return()=>{disposed=true;};
}
