import { escape, captureLabel } from './observation-display.js';
import { mountSummarySharing } from './summary-sharing.js';
import { validDate } from '../convex/lib/observationTiming.ts';

export function mountPeriodSummary(root,session,patient,onBack) {
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(Date.now());
  let start=new Date(Date.parse(`${today}T12:00:00Z`)-13*86400000).toISOString().slice(0,10),end=today,busy=false,error='',result=null,disposed=false,sharing=false;
  let sharingDraft={text:null,originalText:null},disposeSharing=()=>{};
  const hasEdits=()=>sharingDraft.text!==null && sharingDraft.text!==sharingDraft.originalText;
  const canDiscard=()=>!hasEdits() || window.confirm('This will clear your sharing edits. Your saved health notes will stay unchanged. Continue?');
  function dateLabel(value){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));}
  function periodLabel(){if(start===end)return dateLabel(end);const first=start.slice(0,4)===end.slice(0,4)?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${start}T12:00:00Z`)):dateLabel(start);return `${first} to ${dateLabel(end)}`;}
  function source(source){return `<li><div><p class="fact-text">${escape(source.event)}</p>${changeLabel(source)}<p class="fact-time">${source.date?escape(dateLabel(source.date)):'Timing not known'}${source.when && !/^(today|yesterday|Not specified|Unknown)$/i.test(source.when)?` · ${escape(source.when)}`:''}</p><details class="summary-source"><summary>View source</summary><p>Evidence: ${escape(source.evidence)}</p>${source.edited?'<p>Corrected by you.</p>':''}<p>${escape({present:'Explicitly present',absent:'Explicitly absent',uncertain:'Uncertain'}[source.polarity] || 'Uncertain')}</p><p class="hint">Captured on ${escape(captureLabel(source))}</p><p class="original-update">${escape(source.supportingWords)}</p></details></div></li>`;}
  function changeLabel(item){const section=result?.sections?.find(section=>section.keys.includes(item.key));return section && ['Reported improvements','Reported worsening or new symptoms'].includes(section.title)?`<p class="hint">${escape(section.title)}</p>`:'';}
  function draw(){if(disposed)return;
    root.innerHTML=`<section class="screen period-summary" aria-labelledby="title"><button class="text-action back" id="summary-back" type="button">Back to timeline</button><h1 id="title" tabindex="-1">${escape(patient.name)}’s health summary</h1><p>For you or a doctor visit: a little perspective on the notes you’ve kept.</p>${result?`<details class="summary-period-picker"><summary><span class="selected-period">${escape(periodLabel())}</span><span class="change-dates">Change dates</span></summary>`:''}<form id="summary-period" novalidate><div class="period-dates"><div><label for="period-start">From</label><input id="period-start" type="date" value="${start}" ${busy?'disabled':''}></div><div><label for="period-end">To</label><input id="period-end" type="date" value="${end}" ${busy?'disabled':''}></div></div><p class="hint">Based on when things happened; uncertain dates stay separate.</p><button class="primary account-start" type="submit" ${busy?'disabled':''}>${busy?'Preparing your summary…':'Prepare summary'}</button></form>${result?'</details>':''}${busy?'<p role="status">Reading the saved notes for this period.</p>':''}${error?`<p class="error" role="alert">${escape(error)}</p>`:''}
    ${result?`<div class="period-result" aria-live="polite" tabindex="-1">
      ${result.status==='empty'?'<p>There are no dated updates to summarise for this period.</p>':result.status==='too_many'?`<p>${escape(result.message)}</p>`:`<section class="summary-overview" aria-labelledby="overview-title"><h2 id="overview-title">What the updates tell us</h2><p class="summary-narrative">${result.overview?.length?escape(result.overview.map(item=>item.text).join(' ')):`There isn’t enough information to describe how ${escape(patient.name)}’s health has changed yet. Add more updates to build a fuller picture.`}</p>${result.overview?.length?`<details class="overview-sources"><summary>Notes behind this overview</summary><ul class="update-facts">${[...new Set(result.overview.flatMap(item=>item.keys))].map(key=>source(result.sources.find(item=>item.key===key))).join('')}</ul></details>`:''}<p class="hint">Based on ${result.recordCount} saved ${result.recordCount===1?'update':'updates'} in this period.</p>${result.recordCount<=2?'<p class="summary-limited">This is based on only a few updates, so it gives a limited picture of this period.</p>':''}</section><button class="primary summary-review-share" id="review-share" type="button">Review &amp; share</button><div class="summary-categories">${result.groups.map(group=>`<details class="summary-category"><summary>${categoryIcon(group.title)}<span><h3>${escape(categoryLabel(group.title))}</h3><span class="hint">${group.keys.length} recorded ${group.keys.length===1?'detail':'details'}</span></span><svg class="category-chevron" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m9 5 7 7-7 7"/></svg></summary><ul class="update-facts">${group.keys.map(key=>source(result.sources.find(item=>item.key===key))).join('')}</ul></details>`).join('')}</div>${result.discussionKeys?.length?`<details class="summary-category summary-discussion"><summary>${categoryIcon('Care and visits')}<span><h3>Points to discuss at a visit</h3><span class="hint">${result.discussionKeys.length} recorded ${result.discussionKeys.length===1?'detail':'details'}</span></span><svg class="category-chevron" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m9 5 7 7-7 7"/></svg></summary><p class="hint">Saved questions and notes behind the overview, for you to review.</p><ul class="update-facts">${result.discussionKeys.map(key=>source(result.sources.find(item=>item.key===key))).join('')}</ul></details>`:''}<details class="summary-prepared"><summary>About this summary</summary><p class="hint">Prepared ${escape(captureLabel({capturedAt:result.generatedAt,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}))}. Based only on saved updates; days without notes tell us nothing about symptoms.</p></details>`}
      ${result.undatedCount?`<details class="undated-summary"><summary>${result.undatedCount} ${result.undatedCount===1?'detail with uncertain timing':'details with uncertain timing'}</summary><p class="hint">These were recorded in this period, but we don’t know when they happened. They are separate from the dated summary.</p><ul class="update-facts">${result.undated.map(source).join('')}</ul>${result.undatedCount>result.undated.length?`<p class="hint">Showing the first ${result.undated.length} undated details.</p>`:''}</details>`:''}</div>`:''}</section>`;
    root.querySelector('#summary-back').onclick=()=>{if(!canDiscard())return;disposed=true;disposeSharing();onBack();};
    root.querySelector('#review-share')?.addEventListener('click',()=>{sharing=true;draw();});
    if(sharing && result?.status==='ready'){const back=root.querySelector('#summary-back');back.textContent='Back to summary';back.onclick=()=>{disposeSharing();sharing=false;draw();root.querySelector('#review-share')?.focus();};root.querySelector('.summary-period-picker').hidden=true;root.querySelector('.period-summary > p').hidden=true;root.querySelector('.period-result').removeAttribute('aria-live');root.querySelector('.period-result').innerHTML='<div id="summary-sharing"></div>';disposeSharing();disposeSharing=mountSummarySharing(root.querySelector('#summary-sharing'),session,patient,{start,end},result,sharingDraft);}
    function change(){if(!canDiscard()){root.querySelector('#period-start').value=start;root.querySelector('#period-end').value=end;return;}disposeSharing();sharingDraft={text:null,originalText:null};start=root.querySelector('#period-start').value;end=root.querySelector('#period-end').value;result=null;error='';const period=root.querySelector('.selected-period');if(period)period.textContent=validDate(start)&&validDate(end)&&start<=end?periodLabel():'Choose dates';root.querySelector('.period-result')?.remove();root.querySelector('[role="alert"]')?.remove();}
    root.querySelector('#period-start').oninput=change;root.querySelector('#period-end').oninput=change;
    root.querySelector('#summary-period').onsubmit=async event=>{event.preventDefault();if(busy)return;if(!canDiscard())return;sharingDraft={text:null,originalText:null};disposeSharing();if(!validDate(start)||!validDate(end)||start>end){error='Choose valid dates, with the start before the end.';result=null;draw();return;}busy=true;error='';result=null;draw();try{const response=await session.generateSummary({patientId:patient.id,start,end});if(disposed)return;result=response;}catch{if(disposed)return;error='Busy right now. Try again in a few minutes. Your saved notes are still there.';}busy=false;draw();root.querySelector('.period-result')?.focus();};
  }
  const beforeLeave=event=>{if(hasEdits()){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeLeave);
  draw();root.querySelector('h1').focus();return()=>{disposed=true;disposeSharing();window.removeEventListener('beforeunload',beforeLeave);};
}

function categoryLabel(title) {
  return {'Symptoms and observations':'Symptoms','Measurements':'Measurements','Care and visits':'Care and visits','Appetite, sleep and energy':'Daily wellbeing'}[title] || title;
}
function categoryIcon(title) {
  const icons={
    'Symptoms and observations':['note','<path d="M7 4h8l3 3v13H6V4h1Z M14 4v4h4 M9 12h6 M9 16h4"/>'],
    'Measurements':['measurement','<rect x="5" y="4" width="14" height="16" rx="3"/><path d="M8 9h8 M8 14h2l2-3 2 5 2-2"/>'],
    'Care and visits':['care','<path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2 M5 7h14v13H5Z M12 10v7 M9 13.5h6"/>'],
    'Appetite, sleep and energy':['wellbeing','<path d="M17 3a8 8 0 1 0 4 13A8 8 0 0 1 17 3Z"/>']
  };
  const [kind,path]=icons[title] || icons['Symptoms and observations'];
  return `<span class="category-icon marker-${kind}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${path}</svg></span>`;
}
